# Generated by Django 4.1 on 2022-09-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_post_date_alter_post_deadline"),
    ]

    operations = [
        migrations.RenameModel(old_name="Post", new_name="Job",),
    ]
