# Generated by Django 4.1 on 2022-09-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_post_job"),
    ]

    operations = [
        migrations.RenameModel(old_name="Job", new_name="Scholarship",),
    ]
