# Generated by Django 4.1 on 2022-09-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_job_scholarship"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="title",
            field=models.CharField(default="title", max_length=100),
        ),
    ]
