# Generated by Django 4.1 on 2022-09-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_rename_image_scholarship_header_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scholarship", old_name="header_image", new_name="image",
        ),
    ]
