# Generated by Django 4.1 on 2022-09-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_community"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(default="others", max_length=255)),
                ("deadline", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
