# Generated by Django 4.1 on 2022-09-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_job_number_job_women"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
