# Generated by Django 4.1 on 2022-09-24 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_hire"),
    ]

    operations = [
        migrations.AddField(
            model_name="hire",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
