# Generated by Django 4.1 on 2022-09-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_alter_blog_body_alter_job_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="community",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fellowship",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hire",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="image",
            field=models.ImageField(
                blank=True, default="images/alamin.jpg", null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
