# Generated by Django 4.1 on 2022-10-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_job_image_alter_community_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="link",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="blog",
            name="header_image",
            field=models.ImageField(
                blank=True, default="chevening.png", null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="image",
            field=models.ImageField(
                blank=True, default="chevening.png", null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True, default="chevening.png", null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="fellowship",
            name="image",
            field=models.ImageField(
                blank=True, default="chevening.png", null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.ImageField(
                blank=True, default="chevening.png", null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="image",
            field=models.ImageField(
                blank=True, default="chevening.png", null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="image",
            field=models.ImageField(
                blank=True, default="chevening.png", null=True, upload_to="images/"
            ),
        ),
    ]
