# Generated by Django 4.1 on 2022-10-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_track_link_alter_blog_header_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/chevening.png",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
