# Generated by Django 4.1 on 2022-10-11 22:33

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_rename_sub_title_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="body",
            field=ckeditor.fields.RichTextField(
                blank=True, default=django.utils.timezone.now, max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="header_image",
            field=models.ImageField(default="chevening.png", upload_to="images/"),
        ),
    ]
