# Generated by Django 4.1 on 2022-10-11 23:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_alter_blog_body_alter_blog_header_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="author",),
        migrations.AlterField(
            model_name="blog",
            name="body",
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
