# Generated by Django 4.1 on 2022-10-15 15:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_article_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="article", name="body", field=ckeditor.fields.RichTextField(),
        ),
    ]
