# Generated by Django 4.1 on 2022-10-15 15:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_job_description_alter_article_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
    ]
