# Generated by Django 4.1 on 2022-10-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_job_link_alter_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="link",
            field=models.CharField(default="https://www.yandytech.com", max_length=255),
        ),
    ]
