# Generated by Django 4.1 on 2022-10-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_alter_job_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job", name="link", field=models.CharField(max_length=255),
        ),
    ]
