# Generated by Django 4.1 on 2023-01-10 00:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0041_alter_article_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="new_slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
