# Generated by Django 4.1 on 2023-01-20 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0043_hire_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="hire",
            name="image",
            field=models.ImageField(default=django.utils.timezone.now, upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hire",
            name="cv",
            field=models.FileField(default="chevening.png", upload_to="images/"),
        ),
    ]
