# Generated by Django 4.1 on 2023-01-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0044_hire_image_alter_hire_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cv/"),
        ),
        migrations.AlterField(
            model_name="hire",
            name="image",
            field=models.ImageField(default="chevening.png", upload_to="images/"),
        ),
    ]
