# Generated by Django 4.1 on 2023-01-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_remove_hire_image_alter_hire_cv"),
    ]

    operations = [
        migrations.RemoveField(model_name="hire", name="cv",),
    ]
