# Generated by Django 4.1 on 2023-01-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0048_hire_cv"),
    ]

    operations = [
        migrations.RenameField(model_name="hire", old_name="cv", new_name="cv_upload",),
    ]
