# Generated by Django 4.1 on 2023-01-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0049_rename_cv_hire_cv_upload"),
    ]

    operations = [
        migrations.RemoveField(model_name="hire", name="cv_upload",),
        migrations.AddField(
            model_name="hire",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="media/cv/"),
        ),
    ]
