# Generated by Django 4.1 on 2023-01-21 14:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0051_remove_job_cv_alter_hire_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
