# Generated by Django 4.1.7 on 2023-03-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0054_event_slug_track_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
