# Generated by Django 4.1.7 on 2023-03-07 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0057_article_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="category",),
    ]
