# Generated by Django 4.1.7 on 2023-03-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0058_remove_article_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcategory",
            name="name",
            field=models.CharField(default=1, max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
