# Generated by Django 4.1.7 on 2023-03-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0059_alter_blogcategory_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
