# Generated by Django 4.1.7 on 2023-03-08 09:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0062_alter_comment_options_rename_date_comment_created_on_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="new_slug",),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
        migrations.DeleteModel(name="Blog",),
    ]
