# Generated by Django 4.2 on 2023-04-22 23:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0064_job_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="%(id)s",
                editable=False,
                null=True,
                populate_from="position",
                unique=True,
            ),
        ),
    ]
