# Generated by Django 4.2 on 2023-04-22 23:26

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0066_alter_job_id_alter_job_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="%(id)s",
                editable=False,
                null=True,
                populate_from="position",
                unique=True,
            ),
        ),
    ]
